const apiRoutes = {
  authentication: {
    login: '/authentication/login',
    logout: '/authentication/logout',
    recovery: '/authentication/recovery',
    refreshToken: '/authentication/refresh-token',
    verifyToken: '/authentication/verify-token',
    checkPasswordResetToken: '/authentication/check-reset-password-token',
    resetPassword: '/authentication/reset-password',
    verifyEmail: '/authentication/verify-email',
    verifyPassword: '/authentication/verify-password',
  },
  building: {
    list: '/building',
    detail: (buildingId: number) => `/building/${buildingId}`,
    room: (buildingId: number) => `/building/${buildingId}/room`,
    service: (buildingId: number) => `/building/${buildingId}/service`,
    roomDetail: (buildingId: number, roomId: number) => `/building/${buildingId}/room/${roomId}`,
    add: '/building/add',
    delete: (buildingID: number) => `/building/${buildingID}`,
    deleteRooms: (buildingID: number) => `/building/${buildingID}/deleteRooms`,
    deleteServices: (buildingID: number) => `/building/${buildingID}/deleteServices`,
    addService: (buildingID: number) => `/building/${buildingID}/service/add`,
    editService: (buildingID: number, servicerID: number) => `/building/${buildingID}/service/${servicerID}/edit`,
    addRoom: (buildingID: number) => `/building/${buildingID}/room/add`,
    getSchedule: (buildingID: number) => `/building/${ buildingID }/schedule`,
    updateBuilding: (buildingID: number) => `/building/${ buildingID }/update`,
  },
  room: {},
  profile: {},
  staff: {
    list: '/staff',
    detail: (staffId: number) => `/staff/${staffId}`,
    add: '/staff',
  },
  customer: {
    list: '/customer',
    detail: (customerId: number) => `/customer/${customerId}`,
    add: '/customer',
  },
  bill: {
    list: '/bill',
    detail: (billId: number) => `/bill/${billId}`,
    add: '/bill/add',
  },
  support_ticket: {},
  notice: {},
  contract: {},
  import: {},
};

export { apiRoutes };
