const apiRoutes = {
  authentication: {
    login: '/authentication/login',
    logout: '/authentication/logout',
    recovery: '/authentication/recovery',
    refreshToken: '/authentication/refresh-token',
    verifyToken: '/authentication/verify-token',
    checkPasswordResetToken: '/authentication/check-reset-password-token',
    resetPassword: '/authentication/reset-password',
    verifyEmail: '/authentication/verify-email',
    verifyPassword: '/authentication/verify-password',
  },
  building: {
    list: '/building',
    detail: (buildingId: number) => `/building/${buildingId}`,
    room: (buildingId: number) => `/building/${buildingId}/room`,
    service: (buildingId: number) => `/building/${buildingId}/service`,
    roomDetail: (buildingId: number, roomId: number) => `/building/${buildingId}/room/${roomId}`,
    add: '/building/add',
    delete: (buildingID: number) => `/building/${buildingID}`,
    deleteRooms: (buildingID: number) => `/building/${buildingID}/deleteRooms`,
    deleteServices: (buildingID: number) => `/building/${buildingID}/deleteServices`,
    addService: (buildingID: number) => `/building/${buildingID}/service/add`,
  },
  room: {},
  profile: {},
  staff: {},
  customer: {},
  bill: {},
  support_ticket: {},
  notice: {},
  contract: {},
  import: {},
};

export { apiRoutes };
