// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/6/2025, 4:14:45 PM
const configMerger = require("H:/Projects/Appartment-Management-System-Client/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["H:/Projects/Appartment-Management-System-Client/components/**/*.{vue,js,jsx,mjs,ts,tsx}","H:/Projects/Appartment-Management-System-Client/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","H:/Projects/Appartment-Management-System-Client/components/**/*.{vue,js,jsx,mjs,ts,tsx}","H:/Projects/Appartment-Management-System-Client/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","H:/Projects/Appartment-Management-System-Client/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","H:/Projects/Appartment-Management-System-Client/plugins/**/*.{js,ts,mjs}","H:/Projects/Appartment-Management-System-Client/composables/**/*.{js,ts,mjs}","H:/Projects/Appartment-Management-System-Client/utils/**/*.{js,ts,mjs}","H:/Projects/Appartment-Management-System-Client/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","H:/Projects/Appartment-Management-System-Client/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","H:/Projects/Appartment-Management-System-Client/app.config.{js,ts,mjs}"] } }));

module.exports = config
